[package]
name = "browser_engine"
version = "0.1.0"
authors = ["Erick <erick.8bld@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
